### ISSUE TITLE
Error when run the sample app in WebIDE

### ISSUE THREAD

**Issue by jcortesp** [SAP-samples/s4hana-ext-microservice#1] opened 2020-07-29 00:58 UTC
Hi,
I followed the steps sticking on the guides but when I run the app in SCP (run in browser) the following error appeared:

{
	"requestUri": "/S4HC_BO_FaultyAddress/sap/opu/odata/sap/YY1_FAULTYADDRESS_CDS/$metadata",
	"statusCode": 403,
	"statusText": "",
	"headers": [],
	"body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>/IWFND/CM_CONSUMER/101</code><message xml:lang=\"en\">No authorization to access Service 'YY1_FAULTYADDRESS_CDS_0001'</message><innererror><application><component_id/><service_namespace>/SAP/</service_namespace><service_id>YY1_FAULTYADDRESS_CDS</service_id><service_version>0001</service_version></application><transactionid>F1B631EA21110620E005F1BBF2092CBE</transactionid><timestamp>20200729005706.8609510</timestamp><Error_Resolution><SAP_Transaction>For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details</SAP_Transaction><SAP_Note>See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)</SAP_Note></Error_Resolution><errordetails/></innererror></error>"
}

I think there is a problem in the code because the uri must be filled whit my S4hana tenat.

Thank you

**Comment by grenik** [comment] 2020-07-29 09:30
Hello jcortesp,

I've moved your issue to this repository because it is the only sample that [uses the CDS view](https://github.com/search?q=org%3ASAP-samples+YY1_FAULTYADDRESS_CDS&type=Code) that you've mentioned.

The error that you are getting is coming from SAP S/4HANA Cloud which means that your request has reached it via a respective destination on SAP Cloud Platform.

The error code `HTTP 403 Forbidden` and the error message `No authorization to access Service 'YY1_FAULTYADDRESS_CDS_0001'` usually mean one of the following:
1. You didn't maintain Basic authentication details in the destination configuration or the username and/or the password are wrong. In your destination configuration, you must use the same username and password that are used in the respective communication arrangement in SAP S/4HANA Cloud:
![image](https://user-images.githubusercontent.com/39084120/88780035-b32d3d80-d18a-11ea-9a37-fc147359ed80.png)
Related setup guide steps are [Create Communication Arrangement](https://help.sap.com/viewer/63aaaca3eb4a41d0958ad433df0c0290/SHIP/en-US/edac6556f6604c69ad22d382817efb29.html) and [Destination for SAP S/4HANA](https://help.sap.com/viewer/63aaaca3eb4a41d0958ad433df0c0290/SHIP/en-US/dff1c2b0999c4d9f8d96717e770ae766.html).

2. Your technical user is locked due to numerous invalid authentication attempts, e.g. because you maintained a false password in your destination configuration and then launched the application several times. You can unlock the user using the "Display Technical Users" application in your SAP S/4HANA Cloud. If a user is locked, you will see a lock icon in the "Locked" column. In such case, select the user and click the "Unlock" button.
![image](https://user-images.githubusercontent.com/39084120/88780582-7ca3f280-d18b-11ea-801e-72841afec8da.png)
To be on the safe side, you can also click the "Edit" button and specify a new password. Then, maintain the new password in your destination.

When updating the destination configuration, please note that it takes several minutes until your application gets the updated configuration. If you try to open the application in the meantime, your technical user may get locked again because of outdated invalid authentication details. To ensure that the destination configuration is updated, you can restart the application manually as it is shown on the screenshot below:
![image](https://user-images.githubusercontent.com/39084120/88781302-8417cb80-d18c-11ea-86c9-46c5decfa22b.png)

> I think there is a problem in the code because the uri must be filled whit my S4hana tenat.

It won't be filled: HTML5 runtime on Neo "maps" a relative URL of your HTML5 application to a URL in your destination. The mapping is maintained in your [application descriptor](https://github.com/SAP-samples/s4hana-ext-microservice/blob/69b2d3893fa1b985adc56e4078cf9821bfde0d38/neo-app.json#L26). To call your SAP S/4HANA Cloud system API, your application simply calls its relative path, e.g.
```
https://your-app-url/your-destination-relative-path/sap/opu/odata/sap/YY1_FAULTYADDRESS_CDS/
```
The call is then forwarded by the HTML5 runtime to your SAP S/4HANA Cloud tenant. You can read more about it [here](https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US/d6c8347494ce4b48864dfabb42d0d207.html).

If it solves your problem, please feel free to close the issue.

Best regards,
Nikolay

**Comment by grenik** [comment] 2021-04-06 11:03
Closing the issue due to inactivity. Feel free to reopen it if the issue is still valid.

**Closed as completed by grenik** 2021-04-06 11:03 UTC
